apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ag0eho2mw-python 
  janus-idp.io/tekton: ag0eho2mw-python
  backstage.io/kubernetes-id: ag0eho2mw-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ag0eho2mw-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml