apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ag0eho2mw-python-gitops
  description: This is GitOps manifest for ag0eho2mw-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=ag0eho2mw-python
    backstage.io/kubernetes-id: ag0eho2mw-python 
    backstage.io/techdocs-ref: dir:. 
    jenkins.io/job-full-name: ag0eho2mw-python-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ag0eho2mw-python
