apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: ag0eho2mw-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ag0eho2mw-python 
  name: ag0eho2mw-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: ag0eho2mw-python
    weight: 100 
