apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ag0eho2mw-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ag0eho2mw-python 
  name: ag0eho2mw-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ag0eho2mw-python 
